### ISSUE TITLE
新频道

### ISSUE THREAD

**Issue by Kingstonzhang** [oudoubleyang/Univinfo#2]
新频道加入NUFE
https://t.me/nufeisdone

**Comment by oudoubleyang** [comment]
已加入，稍后同步

**Comment by oudoubleyang** [comment]
已同步

**Comment by Kingstonzhang** [comment]
感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: KumaTea <notifications@github.com&gt;
发送时间: 2019年10月18日 12:17
收件人: oudoubleyang/Univinfo <Univinfo@noreply.github.com&gt;
抄送: Kingstonzhang <847905262@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[oudoubleyang/Univinfo] 新频道 (#2)




已同步
